// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/Header";
import ActiveSectionContextProvider from "./context/active-section-context";
import StarsCanvas from "./components/StarBackground";
import Footer from "./components/Footer";
import ThemeContextProvider from "./context/theme-context";
import { Toaster } from "react-hot-toast";
import ThemeSwitch from "./components/Theme-switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mukhil Baskaran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}
      >
        <div className="absolute inset-0 -z-10 h-full w-full bg-[radial-gradient(125%_125%_at_50%_10%,rgba(255,223,236,0.8)_10%,rgba(138,43,226,0.8)_60%)] dark:bg-[radial-gradient(125%_125%_at_50%_10%,rgba(0,0,0,0.8)_10%,rgba(99,14,255,0.8)_60%)]"></div>{" "}
        <ThemeContextProvider>
          <ActiveSectionContextProvider>
            <Header />
            <StarsCanvas />
            <main className="min-h-screen">{children}</main>
            <Footer />
            <Toaster position="top-right" />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
